### ISSUE TITLE
Make extension name register opt-in

### ISSUE THREAD

**Issue by Riajyuu** [wismna/ModernKeePass#10]
Since I also use other client, now ModernKeePass will mess up the extension name handler.

**Comment by wismna** [comment]
Hi,

Actually, this is not something I control. The app is registered in the Windows Store as being able to open these files, so Windows automatically registers the app as a handler for the kdbx extension.

However, you can easily change this: right-click on a kdbx file, click Open with, and in the menu that appears, click on "Always use this app .kdbx files", then choose the app you prefer.
