### ISSUE TITLE
Cannot save database without StorageFile

### ISSUE THREAD

**Issue by marcscol** [wismna/ModernKeePass#2]
I am trying to create a new database file without providing the Storage File. I am getting an object null reference exception.

            this.KeePassDatabase.New(connectionInfo, compositeKey);
            this.KeePassDatabase.Save(new StatusLogger());

I think this StorageFile is never created if I call new with the information provided above.

Regards

**Comment by wismna** [comment]
Hi,

Yes, the StorageFile is mandatory, as WinRT or UWP apps can't arbitrarily open or create files: it needs to be done via user action (e.g from a file of folder picker control), except in certain folders, such as app root folder, or user temporary folder.
This is why the StorageFile is mandatory.

Regards

**Comment by marcscol** [comment]
In that case, maybe it's a good option to remove the IOConnectionInfo constructor with only the file path, because this can lead to null references inside your lib.

**Comment by wismna** [comment]
You're right! I'll remove it in the next version.

**Comment by wismna** [comment]
Took a while, but it's finally removed (plus has lots of other changes too) !
