### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by b0110101001110011** [wismna/ModernKeePass#5]
When I compile and run in  debug mode, if I try to create a new Database I get 
System.NullReferenceException: 'Object reference not set to an instance of an object.' on  Line 118 of the CompositeKeyUserControl?

**Comment by wismna** [comment]
Are you compiling the latest source ? If yes, it's a work in progress in migrating the "old" version to Windows 10 UWP, so many things might be broken. It will be corrected in time, though :)

**Comment by b0110101001110011** [comment]
Yes, I'm using the latest

**Comment by wismna** [comment]
Closing as the source has been updated a lot recently
