### ISSUE TITLE
{"Buffer cannot be null. (Parameter 'buffer')"} exception when opening DB 

### ISSUE THREAD

**Issue by RiggerJay** [wismna/ModernKeePass#9]
Using the code example below,   I get exception when opening the DB

of course I changed the path and masterpw..  ;)

---------------------------------
var dbpath = @"C:\path\to\passwords.kdbx";
var masterpw = "Your$uper$tr0ngMst3rP@ssw0rd";

var ioConnInfo = new IOConnectionInfo { Path = dbpath };
var compKey = new CompositeKey();
compKey.AddUserKey(new KcpPassword(masterpw));

var db = new KeePassLib.PwDatabase();
db.Open(ioConnInfo, compKey, null);

var kpdata = from entry in db.RootGroup.GetEntries(true)
                select new
                {
                    Group = entry.ParentGroup.Name,
                    Title = entry.Strings.ReadSafe("Title"),
                    Username = entry.Strings.ReadSafe("UserName"),
                    Password = entry.Strings.ReadSafe("Password"),
                    URL = entry.Strings.ReadSafe("URL"),
                    Notes = entry.Strings.ReadSafe("Notes")

                };                                                                                  

kpdata.Dump(); // this is how Linqpad outputs stuff
db.Close();

**Comment by RiggerJay** [comment]
I guess never mind... this was meant for ModernKeypassLib

**Comment by wismna** [comment]
Hi,

I work on both, so don't worry. I will create a Readme file on the ModernKeePassLib project explaining how to use it. I agree it's not as easy as it looks, because I tried to do minimal changes in the original code, so the workflow can be a bit twisted.
The thing is, you can't use a file path to create a IOConnectionInfo. Instead, IOConnectionInfo requires a byte array, like so:

`var ioConnection = IOConnectionInfo.FromByteArray(byte_array);`

Then you can open your database.
(I did this to remove the dependency on the file system.)

**Comment by wismna** [comment]
Hi,

I updated the readme to give info on how to use the library.
Please let me know if this works for you.
[Readme](https://github.com/wismna/ModernKeePassLib)

**Comment by suanmb** [comment]
`var dbpath = @"c:\Database2.kdbx";
//var keypath = @"\\xxx\Desktop\KeePassDatabase\Database.key";
var masterpw = "123456";

var ioConnInfo = IOConnectionInfo.FromByteArray(File.ReadAllBytes(dbpath));
var compKey = new CompositeKey();
compKey.AddUserKey(new KcpPassword(masterpw));
//compKey.AddUserKey(new KcpKeyFile(IOConnectionInfo.FromPath(keypath)));

var db = new PwDatabase();
db.Open(ioConnInfo, compKey, new NullStatusLogger());

//var kpdata = from entry in db.RootGroup.GetEntries(true)
//             select new
//             {
//                 Group = entry.ParentGroup.Name,
//                 Title = entry.Strings.ReadSafe("Title"),
//                 Username = entry.Strings.ReadSafe("UserName"),
//                 Password = entry.Strings.ReadSafe("Password"),
//             };

//Console.WriteLine(string.Join(Environment.NewLine, kpdata));
db.Close();`

I used the above code, but why would it give me this error?


未经处理的异常:  System.InvalidOperationException: 节点类型 Attribute 上不支持 ReadElementContentAsString 方法。 行 34，位置 19。
   在 System.Xml.XmlReader.SetupReadElementContentAsXxx(String methodName)
   在 System.Xml.XmlReader.ReadElementContentAsString()
   在 ModernKeePassLib.Serialization.KdbxFile.ReadBase64(XmlReader xr, Boolean bRaw)
   在 ModernKeePassLib.Serialization.KdbxFile.ReadProtectedBinary(XmlReader xr)
   在 ModernKeePassLib.Serialization.KdbxFile.ReadXmlElement(KdbContext ctx, XmlReader xr)
   在 ModernKeePassLib.Serialization.KdbxFile.ReadDocumentStreamed(XmlReader xr, Stream sParentStream)
   在 ModernKeePassLib.Serialization.KdbxFile.ReadXmlStreamed(Stream sXml, Stream sParent)
   在 ModernKeePassLib.Serialization.KdbxFile.Load(Stream sSource, KdbxFormat fmt, IStatusLogger slLogger)
   在 ModernKeePassLib.PwDatabase.Open(IOConnectionInfo ioSource, CompositeKey pwKey, IStatusLogger slLogger)
   在 ConsoleApp1.Program.Main(String[] args) 位置 C:\Users\ygct\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:行号 28请按任意键继 续. . .
